export const CATEGORY_TITLES = [
  'Action',
  'Adventure',
  'Animation',
  'Comedy',
  'Crime',
  'Drama',
  'Fantasy',
  'Horror',
  'Mystery',
  'Romance',
  'Sci-Fi',
  'Thriller',
] as const

export const STREAMINGS = [
  { title: 'Netflix', imgUrl: 'https://picsum.photos/seed/netflix/200/200' },
  { title: 'Prime Video', imgUrl: 'https://picsum.photos/seed/primevideo/200/200' },
  { title: 'Disney+', imgUrl: 'https://picsum.photos/seed/disneyplus/200/200' },
  { title: 'Max', imgUrl: 'https://picsum.photos/seed/hbomax/200/200' },
  { title: 'Apple TV+', imgUrl: 'https://picsum.photos/seed/appletv/200/200' },
  { title: 'Paramount+', imgUrl: 'https://picsum.photos/seed/paramount/200/200' },
  { title: 'Hulu', imgUrl: 'https://picsum.photos/seed/hulu/200/200' },
  { title: 'Peacock', imgUrl: 'https://picsum.photos/seed/peacock/200/200' },
  { title: 'Crunchyroll', imgUrl: 'https://picsum.photos/seed/crunchyroll/200/200' },
  { title: 'Star+', imgUrl: 'https://picsum.photos/seed/starplus/200/200' },
] as const

export type SeedMovie = {
  title: string
  description: string
  releaseYear: number
  durationInMinutes: number
  categories: string[]
  streamings: string[]
}

export const MOVIES: SeedMovie[] = [
  {
    title: 'The Godfather',
    description: 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.',
    releaseYear: 1972,
    durationInMinutes: 175,
    categories: ['Crime', 'Drama'],
    streamings: ['Netflix', 'Paramount+'],
  },
  {
    title: 'The Dark Knight',
    description: 'Batman faces the Joker, a criminal mastermind who plunges Gotham into chaos.',
    releaseYear: 2008,
    durationInMinutes: 152,
    categories: ['Action', 'Crime', 'Thriller'],
    streamings: ['Max', 'Netflix'],
  },
  {
    title: 'Inception',
    description: 'A thief who steals corporate secrets through dream-sharing is given a chance to redeem himself.',
    releaseYear: 2010,
    durationInMinutes: 148,
    categories: ['Action', 'Sci-Fi', 'Thriller'],
    streamings: ['Netflix', 'Prime Video'],
  },
  {
    title: 'Pulp Fiction',
    description: 'The lives of two mob hitmen, a boxer and a pair of diner bandits intertwine in Los Angeles.',
    releaseYear: 1994,
    durationInMinutes: 154,
    categories: ['Crime', 'Drama'],
    streamings: ['Paramount+', 'Hulu'],
  },
  {
    title: 'Forrest Gump',
    description: 'The presidencies of Kennedy and Johnson unfold through the life of a man with a low IQ.',
    releaseYear: 1994,
    durationInMinutes: 142,
    categories: ['Drama', 'Romance'],
    streamings: ['Paramount+', 'Netflix'],
  },
  {
    title: 'The Matrix',
    description: 'A computer hacker learns about the true nature of his reality and his role in the war against its controllers.',
    releaseYear: 1999,
    durationInMinutes: 136,
    categories: ['Action', 'Sci-Fi'],
    streamings: ['Max', 'Prime Video'],
  },
  {
    title: 'Interstellar',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanitys survival.',
    releaseYear: 2014,
    durationInMinutes: 169,
    categories: ['Adventure', 'Drama', 'Sci-Fi'],
    streamings: ['Paramount+', 'Apple TV+'],
  },
  {
    title: 'Parasite',
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between two families.',
    releaseYear: 2019,
    durationInMinutes: 132,
    categories: ['Drama', 'Thriller'],
    streamings: ['Hulu', 'Max'],
  },
  {
    title: 'Spirited Away',
    description: 'A young girl enters a world of spirits and must find her way home after her parents are transformed.',
    releaseYear: 2001,
    durationInMinutes: 125,
    categories: ['Animation', 'Adventure', 'Fantasy'],
    streamings: ['Max', 'Netflix'],
  },
  {
    title: 'The Shawshank Redemption',
    description: 'Two imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.',
    releaseYear: 1994,
    durationInMinutes: 142,
    categories: ['Drama'],
    streamings: ['Netflix', 'Prime Video'],
  },
  {
    title: 'Gladiator',
    description: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.',
    releaseYear: 2000,
    durationInMinutes: 155,
    categories: ['Action', 'Adventure', 'Drama'],
    streamings: ['Paramount+', 'Netflix'],
  },
  {
    title: 'Whiplash',
    description: 'A promising young drummer enrolls at a cut-throat music conservatory.',
    releaseYear: 2014,
    durationInMinutes: 106,
    categories: ['Drama'],
    streamings: ['Netflix', 'Hulu'],
  },
  {
    title: 'The Social Network',
    description: 'Harvard student Mark Zuckerberg creates the social networking site that would become Facebook.',
    releaseYear: 2010,
    durationInMinutes: 120,
    categories: ['Drama'],
    streamings: ['Netflix', 'Prime Video'],
  },
  {
    title: 'Mad Max: Fury Road',
    description: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland.',
    releaseYear: 2015,
    durationInMinutes: 120,
    categories: ['Action', 'Adventure', 'Sci-Fi'],
    streamings: ['Max', 'Hulu'],
  },
  {
    title: 'Get Out',
    description: 'A young African-American visits his white girlfriends parents for the weekend, where his uneasiness grows.',
    releaseYear: 2017,
    durationInMinutes: 104,
    categories: ['Horror', 'Mystery', 'Thriller'],
    streamings: ['Peacock', 'Prime Video'],
  },
  {
    title: 'La La Land',
    description: 'A jazz pianist falls for an aspiring actress in Los Angeles.',
    releaseYear: 2016,
    durationInMinutes: 128,
    categories: ['Comedy', 'Drama', 'Romance'],
    streamings: ['Netflix', 'Hulu'],
  },
  {
    title: 'Joker',
    description: 'A mentally troubled stand-up comedian embarks on a downward spiral that leads to the streets of Gotham.',
    releaseYear: 2019,
    durationInMinutes: 122,
    categories: ['Crime', 'Drama', 'Thriller'],
    streamings: ['Max', 'Prime Video'],
  },
  {
    title: 'Dune',
    description: 'Paul Atreides travels to the most dangerous planet in the universe to ensure the future of his family and people.',
    releaseYear: 2021,
    durationInMinutes: 155,
    categories: ['Adventure', 'Drama', 'Sci-Fi'],
    streamings: ['Max', 'Prime Video'],
  },
  {
    title: 'Everything Everywhere All at Once',
    description: 'A Chinese-American woman is swept up in an insane adventure in which she alone can save the universe.',
    releaseYear: 2022,
    durationInMinutes: 139,
    categories: ['Action', 'Adventure', 'Comedy'],
    streamings: ['Paramount+', 'Prime Video'],
  },
  {
    title: 'The Grand Budapest Hotel',
    description: 'A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy.',
    releaseYear: 2014,
    durationInMinutes: 99,
    categories: ['Adventure', 'Comedy', 'Crime'],
    streamings: ['Hulu', 'Disney+'],
  },
  {
    title: 'Coco',
    description: 'Aspiring musician Miguel enters the Land of the Dead to find his great-great-grandfather, a legendary singer.',
    releaseYear: 2017,
    durationInMinutes: 105,
    categories: ['Animation', 'Adventure', 'Fantasy'],
    streamings: ['Disney+'],
  },
  {
    title: 'Spider-Man: Into the Spider-Verse',
    description: 'Teen Miles Morales becomes the Spider-Man of his universe and must join with others to save it.',
    releaseYear: 2018,
    durationInMinutes: 117,
    categories: ['Animation', 'Action', 'Adventure'],
    streamings: ['Netflix', 'Disney+'],
  },
  {
    title: 'The Silence of the Lambs',
    description: 'A young F.B.I. cadet must receive the help of an incarcerated cannibal killer to catch another serial killer.',
    releaseYear: 1991,
    durationInMinutes: 118,
    categories: ['Crime', 'Drama', 'Thriller'],
    streamings: ['Prime Video', 'Hulu'],
  },
  {
    title: 'Alien',
    description: 'The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.',
    releaseYear: 1979,
    durationInMinutes: 117,
    categories: ['Horror', 'Sci-Fi'],
    streamings: ['Disney+', 'Hulu'],
  },
  {
    title: 'Back to the Future',
    description: 'Marty McFly is accidentally sent thirty years into the past in a time-traveling DeLorean.',
    releaseYear: 1985,
    durationInMinutes: 116,
    categories: ['Adventure', 'Comedy', 'Sci-Fi'],
    streamings: ['Netflix', 'Peacock'],
  },
  {
    title: 'Jurassic Park',
    description: 'A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting kids after a power shutdown.',
    releaseYear: 1993,
    durationInMinutes: 127,
    categories: ['Action', 'Adventure', 'Sci-Fi'],
    streamings: ['Peacock', 'Netflix'],
  },
  {
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    description: 'A meek Hobbit and eight companions set out on a journey to destroy the One Ring.',
    releaseYear: 2001,
    durationInMinutes: 178,
    categories: ['Adventure', 'Drama', 'Fantasy'],
    streamings: ['Max', 'Prime Video'],
  },
  {
    title: 'Harry Potter and the Sorcerers Stone',
    description: 'An orphaned boy enrolls in a school of wizardry and learns the truth about himself and his family.',
    releaseYear: 2001,
    durationInMinutes: 152,
    categories: ['Adventure', 'Fantasy', 'Drama'],
    streamings: ['Max', 'Peacock'],
  },
  {
    title: 'The Avengers',
    description: 'Earths mightiest heroes must come together to stop Loki and his alien army from enslaving humanity.',
    releaseYear: 2012,
    durationInMinutes: 143,
    categories: ['Action', 'Adventure', 'Sci-Fi'],
    streamings: ['Disney+'],
  },
  {
    title: 'Black Panther',
    description: 'TChalla returns home to Wakanda to take his rightful place as king.',
    releaseYear: 2018,
    durationInMinutes: 134,
    categories: ['Action', 'Adventure', 'Sci-Fi'],
    streamings: ['Disney+'],
  },
  {
    title: 'Toy Story',
    description: 'A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy.',
    releaseYear: 1995,
    durationInMinutes: 81,
    categories: ['Animation', 'Adventure', 'Comedy'],
    streamings: ['Disney+'],
  },
  {
    title: 'Finding Nemo',
    description: 'A clown fish teams up with a forgetful fish to find his missing son.',
    releaseYear: 2003,
    durationInMinutes: 100,
    categories: ['Animation', 'Adventure', 'Comedy'],
    streamings: ['Disney+'],
  },
  {
    title: 'The Lion King',
    description: 'Lion prince Simba flees his kingdom after the death of his father, only to learn the true meaning of responsibility.',
    releaseYear: 1994,
    durationInMinutes: 88,
    categories: ['Animation', 'Adventure', 'Drama'],
    streamings: ['Disney+'],
  },
  {
    title: 'No Country for Old Men',
    description: 'Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong.',
    releaseYear: 2007,
    durationInMinutes: 122,
    categories: ['Crime', 'Drama', 'Thriller'],
    streamings: ['Paramount+', 'Prime Video'],
  },
  {
    title: 'There Will Be Blood',
    description: 'A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector.',
    releaseYear: 2007,
    durationInMinutes: 158,
    categories: ['Drama'],
    streamings: ['Paramount+', 'Prime Video'],
  },
  {
    title: 'The Prestige',
    description: 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion.',
    releaseYear: 2006,
    durationInMinutes: 130,
    categories: ['Drama', 'Mystery', 'Thriller'],
    streamings: ['Prime Video', 'Hulu'],
  },
  {
    title: 'Arrival',
    description: 'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear.',
    releaseYear: 2016,
    durationInMinutes: 116,
    categories: ['Drama', 'Mystery', 'Sci-Fi'],
    streamings: ['Paramount+', 'Prime Video'],
  },
  {
    title: 'Her',
    description: 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.',
    releaseYear: 2013,
    durationInMinutes: 126,
    categories: ['Drama', 'Romance', 'Sci-Fi'],
    streamings: ['Netflix', 'Prime Video'],
  },
  {
    title: 'Blade Runner 2049',
    description: 'A young blade runner discovers a long-buried secret that leads him to track down former blade runner Rick Deckard.',
    releaseYear: 2017,
    durationInMinutes: 164,
    categories: ['Action', 'Drama', 'Sci-Fi'],
    streamings: ['Netflix', 'Prime Video'],
  },
  {
    title: 'The Witch',
    description: 'A family in 1630s New England is torn apart by the forces of witchcraft, black magic and possession.',
    releaseYear: 2015,
    durationInMinutes: 92,
    categories: ['Drama', 'Fantasy', 'Horror'],
    streamings: ['Hulu', 'Prime Video'],
  },
  {
    title: 'Hereditary',
    description: 'A grieving family is haunted by tragedy and disturbing secrets.',
    releaseYear: 2018,
    durationInMinutes: 127,
    categories: ['Drama', 'Horror', 'Mystery'],
    streamings: ['Prime Video', 'Max'],
  },
  {
    title: 'Knives Out',
    description: 'A detective investigates the death of a patriarch of an eccentric, combative family.',
    releaseYear: 2019,
    durationInMinutes: 130,
    categories: ['Comedy', 'Crime', 'Mystery'],
    streamings: ['Prime Video', 'Netflix'],
  },
  {
    title: 'The Menu',
    description: 'A couple travels to a coastal island to eat at an exclusive restaurant where the chef has prepared a shocking menu.',
    releaseYear: 2022,
    durationInMinutes: 107,
    categories: ['Comedy', 'Horror', 'Thriller'],
    streamings: ['Disney+', 'Hulu'],
  },
  {
    title: 'Oppenheimer',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    releaseYear: 2023,
    durationInMinutes: 180,
    categories: ['Drama', 'Thriller'],
    streamings: ['Peacock', 'Prime Video'],
  },
  {
    title: 'Barbie',
    description: 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land.',
    releaseYear: 2023,
    durationInMinutes: 114,
    categories: ['Adventure', 'Comedy', 'Fantasy'],
    streamings: ['Max', 'Prime Video'],
  },
  {
    title: 'Poor Things',
    description: 'The incredible tale of the fantastical evolution of Bella Baxter, a young woman brought back to life by a brilliant scientist.',
    releaseYear: 2023,
    durationInMinutes: 141,
    categories: ['Comedy', 'Drama', 'Romance'],
    streamings: ['Hulu', 'Disney+'],
  },
  {
    title: 'Your Name',
    description: 'Two teenagers share a profound, magical connection upon discovering they are swapping bodies.',
    releaseYear: 2016,
    durationInMinutes: 106,
    categories: ['Animation', 'Drama', 'Fantasy'],
    streamings: ['Crunchyroll', 'Prime Video'],
  },
  {
    title: 'Princess Mononoke',
    description: 'On a journey to find the cure for a cursed wound, Ashitaka finds himself in the middle of a war between forest gods and miners.',
    releaseYear: 1997,
    durationInMinutes: 134,
    categories: ['Animation', 'Adventure', 'Fantasy'],
    streamings: ['Max', 'Netflix'],
  },
  {
    title: 'The Batman',
    description: 'When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the citys hidden corruption.',
    releaseYear: 2022,
    durationInMinutes: 176,
    categories: ['Action', 'Crime', 'Drama'],
    streamings: ['Max', 'Prime Video'],
  },
  {
    title: 'Top Gun: Maverick',
    description: 'After thirty years, Maverick is still pushing the envelope as a top naval aviator, and must confront ghosts of his past.',
    releaseYear: 2022,
    durationInMinutes: 130,
    categories: ['Action', 'Drama'],
    streamings: ['Paramount+', 'Prime Video'],
  },
]

function slug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

export function movieImgUrl(title: string): string {
  return `https://picsum.photos/seed/${slug(title)}/400/600`
}
